function [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% trainClassifier(trainingData)
%  returns a trained classifier and its validation accuracy.
%  This code recreates the classification model trained in
%  Classification Learner app.
%
%   Input:
%       trainingData: the training data of same data type as imported
%        in the app (table or matrix).
%
%   Output:
%       trainedClassifier: a struct containing the trained classifier.
%        The struct contains various fields with information about the
%        trained classifier.
%
%       trainedClassifier.predictFcn: a function to make predictions
%        on new data. It takes an input of the same form as this training
%        code (table or matrix) and returns predictions for the response.
%        If you supply a matrix, include only the predictors columns (or
%        rows).
%
%       validationAccuracy: a double containing the validation accuracy
%        score in percent. In the app, the History list displays this
%        overall accuracy score for each model.
%
%  Use the code to train the model with new data.
%  To retrain your classifier, call the function from the command line
%  with your original data or new data as the input argument trainingData.
%
%  For example, to retrain a classifier trained with the original data set
%  T, enter:
%    [trainedClassifier, validationAccuracy] = trainClassifier(T)
%
%  To make predictions with the returned 'trainedClassifier' on new data T,
%  use
%    yfit = trainedClassifier.predictFcn(T)
%
%  To automate training the same classifier with new data, or to learn how
%  to programmatically train classifiers, examine the generated code.

% Auto-generated by MATLAB on 2018-05-20 20:50:21


inputTable = trainingData;
% Split matrices in the input table into vectors
inputTable.meas_1 = inputTable.meas(:,1);
inputTable.meas_2 = inputTable.meas(:,2);
inputTable.meas_3 = inputTable.meas(:,3);
inputTable.meas_4 = inputTable.meas(:,4);

% Extract predictors and response
% This code processes the data into the right shape for training the
% classifier.
predictorNames = {'meas_1', 'meas_2', 'meas_3', 'meas_4'};
predictors = inputTable(:, predictorNames);
response = inputTable.species;

% Train a classifier
% This code specifies all the classifier options and trains the classifier.
classificationDiscriminant = fitcdiscr(...
    predictors, ...
    response, ...
    'DiscrimType', 'diagQuadratic', ...
    'FillCoeffs', 'off', ...
    'SaveMemory', 'on', ...
    'ClassNames', {'setosa'; 'versicolor'; 'virginica'});

trainedClassifier.ClassificationDiscriminant = classificationDiscriminant;
splitMatricesInTableFcn = @(t) [t(:,setdiff(t.Properties.VariableNames, {'meas'})), array2table(table2array(t(:,{'meas'})), 'VariableNames', {'meas_1', 'meas_2', 'meas_3', 'meas_4'})];
extractPredictorsFromTableFcn = @(t) t(:, predictorNames);
predictorExtractionFcn = @(x) extractPredictorsFromTableFcn(splitMatricesInTableFcn(x));
discriminantPredictFcn = @(x) predict(classificationDiscriminant, x);
trainedClassifier.predictFcn = @(x) discriminantPredictFcn(predictorExtractionFcn(x));
inputTable = trainingData;
% Split matrices in the input table into vectors
inputTable.meas_1 = inputTable.meas(:,1);
inputTable.meas_2 = inputTable.meas(:,2);
inputTable.meas_3 = inputTable.meas(:,3);
inputTable.meas_4 = inputTable.meas(:,4);

% Extract predictors and response
% This code processes the data into the right shape for training the
% classifier.
predictorNames = {'meas_1', 'meas_2', 'meas_3', 'meas_4'};
predictors = inputTable(:, predictorNames);
response = inputTable.species;


% Perform cross-validation
partitionedModel = crossval(trainedClassifier.ClassificationDiscriminant, 'KFold', 10);

% Compute validation accuracy
validationAccuracy = 1 - kfoldLoss(partitionedModel, 'LossFun', 'ClassifError');

% Compute validation predictions and scores
[validationPredictions, validationScores] = kfoldPredict(partitionedModel);